# Generated by Django 3.2.8 on 2023-07-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookproperty',
            old_name='status',
            new_name='book_status',
        ),
    ]
