# Generated by Django 3.2.8 on 2023-07-11 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')])),
                ('contact_name', models.CharField(max_length=16)),
                ('legal_business_name', models.CharField(max_length=16)),
                ('business_type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=16)),
                ('sub_category', models.CharField(max_length=16)),
                ('registered', models.TextField()),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=50, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_details', to='superadmin.client')),
            ],
        ),
    ]
