# Generated by Django 3.2.8 on 2023-07-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='borded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
