# Generated by Django 3.2.8 on 2023-06-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='terms_and_condition',
        ),
    ]
