# Generated by Django 3.2.8 on 2023-06-20 05:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='superadmin.client'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(upload_to='property', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mpeg4'])], verbose_name='videos'),
        ),
    ]
