# Generated by Django 3.2.8 on 2023-06-22 04:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_remove_properties_terms_and_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor.fields.RichTextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='superadmin.properties')),
            ],
        ),
    ]
