# Generated by Django 3.2.8 on 2023-06-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_rename_adminuser_termsandpolicy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyTerms',
        ),
    ]
