# Generated by Django 3.2.8 on 2023-06-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_propertyterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyterms',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='superadmin.properties'),
        ),
    ]
